name: range-set-list
version: 0.1.1.0
synopsis: Memory efficient sets with continuous ranges of elements.
description: Memory efficient sets with continuous ranges of elements. List based implementation. Interface mimics 'Data.Set' interface where possible.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: MIT
github: phadej/range-set-list
category: Data
tested-with: GHC==7.4.2, GHC==7.6.3, GHC==7.8.4, GHC==7.10.2
extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options: -Wall -fwarn-tabs

dependencies:
  - base        >=4.5      && <4.9
  - semigroups  >=0.16.2.2 && <0.19
  - deepseq     >=1.3.0.0  && <1.5
  - hashable    >=1.2.3.3  && <1.3

library:
  source-dirs: src
  other-extensions:
    - DeriveDataTypeable
    - Safe

tests:
  test:
    main: Tests.hs
    source-dirs: tests
    dependencies:
      - containers        >=0.5 && <0.6
      - tasty             >=0.8 && <0.12
      - tasty-quickcheck  >=0.8 && <0.9
      - range-set-list
